[2017-07-08 15:39:27,015: WARNING/MainProcess] Substantial drift from celery@anton-X451CA may mean clocks are out of sync.  Current drift is
25200 seconds.  [orig: 2017-07-08 15:39:27.015289 recv: 2017-07-08 08:39:27.011533]

[2017-07-08 15:39:45,807: ERROR/MainProcess] Received unregistered task of type 'irr_parser.celery.test'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[["hello"], {}, {"chord": null, "callbacks": null, "chain": null, "errbacks": null}]' (84b)
Traceback (most recent call last):
  File "/home/anton/.local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]
KeyError: 'irr_parser.celery.test'
